services:
  backend:
    build:
      context: .
      dockerfile: VehicleServiceApp/Dockerfile
    ports:
      - "8000:80"

  frontend:
    build:
      context: ./frontend_backup
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
